pipeline {
    agent { docker { image 'maven:3.9.8-eclipse-temurin-21-alpine' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO4vcMLVP1TwG5RpSaqzzklvTynsE+qyP5QRPkIwLx5G danielharary100@gmail.com
